version: '3.8'

services:
  avalanche-node:
    image: avaplatform/avalanchego:latest
    container_name: subnet-studio-avalanche
    ports:
      - "9650:9650"
      - "9651:9651"
    volumes:
      - avalanche-data:/root/.avalanchego
    environment:
      - AVALANCHE_NETWORK_ID=5  # Fuji testnet
    command: >
      --network-id=5
      --http-host=0.0.0.0
      --http-port=9650
      --staking-port=9651
      --public-ip=127.0.0.1
      --staking-tls-cert-file=/root/.avalanchego/staking.crt
      --staking-tls-key-file=/root/.avalanchego/staking.key
      --log-level=info
    restart: unless-stopped
    networks:
      - avalanche-network

  avalanche-cli:
    build:
      context: .
      dockerfile: Dockerfile.avalanche
    container_name: avalanche-cli
    volumes:
      - ./scripts:/avalanche/scripts
      - avalanche-keys:/root/.avalanche
    environment:
      - AVALANCHE_NETWORK=fuji
      - AVALANCHE_PRIVATE_KEY=${AVALANCHE_PRIVATE_KEY:-""}
    depends_on:
      - avalanche-node
    networks:
      - avalanche-network

volumes:
  avalanche-data:
  avalanche-keys:

networks:
  avalanche-network:
    driver: bridge
